#!/usr/bin/env bash
# redirection
sudo apt-get -y update
sudo apt-get -y install nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        location / {
                try_files $/uri $/uri/ =404;
        location /redirect_me{
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                                }
        }
" > /etc/nginx/sites-enabled/default
sudo service nginx restart
