#!/usr/bin/env bash
# redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server;/a rewrite ^/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
