#!/usr/bin/env bash
# load balancer
sudo apt-get update
sudo apt-get upgrade
sudo apt show haproxy
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install haproxy
sudo haproxy -v
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e "
frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend apache_webservers    

backend apache_webservers
    balance roundrobin
    server websvr1	34.138.111.16:80 check
    server websvr2	54.162.185.79:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart