#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
j=1
echo "Hour: 0"
while [ $j -le 13 ]
do
    echo "$i"
	if [ $i = 59 ]
	then
        if [ $j = 13 ]
        then
            break
        fi
        echo "Hour: $j"
        ((j=j+1))
        i=0
    fi
	((i=i+1))
done